"""Contratos e implementações do pipeline experimental de ranking."""

from cinebot_ml.ranking.candidates import (
    CandidateSet,
    CandidateSetValidationError,
    EligibilityPolicy,
    build_candidate_set,
    build_candidate_set_from_config,
)
from cinebot_ml.ranking.contracts import (
    ContractValidationError,
    RankingResult,
    RecommendationItem,
    RecommendationRequest,
    Recommender,
    rank_scored_candidates,
)
from cinebot_ml.ranking.content import (
    ContentConfig,
    ContentConfigError,
    ContentProfile,
    ContentRecommender,
    ItemContent,
    build_content_profile,
    build_item_content,
    content_similarity,
    load_content_config,
)
from cinebot_ml.ranking.popularity import (
    PopularityConfig,
    PopularityConfigError,
    PopularityRecommender,
    bayesian_popularity_score,
    load_popularity_config,
)
from cinebot_ml.ranking.tfidf import (
    TfidfArtifact,
    TfidfConfig,
    TfidfConfigError,
    TfidfRecommender,
    build_movie_document,
    build_profile_document,
    fit_tfidf_artifact,
    load_tfidf_config,
    normalize_text,
)
from cinebot_ml.ranking.supervised import (
    SupervisedArtifact,
    SupervisedConfig,
    SupervisedConfigError,
    SupervisedRecommender,
    assert_supervised_fit_partition,
    assert_supervised_selection_partition,
    build_supervised_frame,
    load_supervised_config,
    validate_supervised_metadata,
)

__all__ = [
    "CandidateSet",
    "CandidateSetValidationError",
    "ContractValidationError",
    "ContentConfig",
    "ContentConfigError",
    "ContentProfile",
    "ContentRecommender",
    "EligibilityPolicy",
    "PopularityConfig",
    "PopularityConfigError",
    "PopularityRecommender",
    "ItemContent",
    "RankingResult",
    "RecommendationItem",
    "RecommendationRequest",
    "Recommender",
    "SupervisedArtifact",
    "SupervisedConfig",
    "SupervisedConfigError",
    "SupervisedRecommender",
    "TfidfArtifact",
    "TfidfConfig",
    "TfidfConfigError",
    "TfidfRecommender",
    "build_candidate_set",
    "build_candidate_set_from_config",
    "build_content_profile",
    "build_item_content",
    "build_movie_document",
    "build_profile_document",
    "build_supervised_frame",
    "bayesian_popularity_score",
    "load_popularity_config",
    "content_similarity",
    "fit_tfidf_artifact",
    "assert_supervised_fit_partition",
    "assert_supervised_selection_partition",
    "load_tfidf_config",
    "load_content_config",
    "load_supervised_config",
    "normalize_text",
    "validate_supervised_metadata",
    "rank_scored_candidates",
]
